### ISSUE TITLE
BUILD FAILED: Compiling for android

### ISSUE THREAD

**Issue by ATOshailesh** [Shin-NiL/shinnilfb#2]
I'm using godot 3.1 and i download latest 3.1 stable godot source code,
Then i follow the steps:

- Copy **GodotFacebook** folder to **godot/modules** folder.

-In terminal
1. $ Scons commad fire
2. $ scons platform=android target=release_debug android_arch=armv7

        [100%] scons: done building targets.

3. cd platform/android/java
4. ./gradlew build **[Get failed]**
![Screen Shot 2019-05-14 at 10 54 45 AM](https://user-images.githubusercontent.com/50569018/57673233-daa4f280-7638-11e9-88e6-e5042376e039.png)

Can you help me with this? What i'm doing wrong?

**Comment by Shin-NiL** [comment]
Please update the module and try again.

**Comment by ATOshailesh** [comment]
I get another solution but i think it's not best solution,
I change this one,

~/platform/android/java/build.gradle
dependencies {
	implementation "com.android.support:support-core-utils:**27.0.2**"  // change 28.0.0 to 27.0.2 
	implementation 'com.facebook.android:facebook-android-sdk:4.33.+' 
}

get success fully build.
Give me another best solution, because i change version every when recompiling code.

**Comment by Shin-NiL** [comment]
Well, I can't find a proper fix to this. The Facebook SDK depends on support 27.0.2 and Godot forces 28.0.0. I've updated the README file giving instructions for removing this dependency manually.
